# Generated by Django 3.0.2 on 2020-01-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalvinTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cnhImg', models.ImageField(upload_to='images/')),
                ('cnhImgUrl', models.URLField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'published_date',
            },
        ),
    ]
