# Generated by Django 3.0.2 on 2020-01-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnh', '0002_auto_20200124_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calvintbl',
            name='published_date',
            field=models.DateField(default='2020-01-25'),
        ),
    ]
